name: geburtstags_app
description: App fÃ¼r Geburtstagerinnerungen
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ^3.13.5

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.1
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  riverpod_annotation: ^2.1.6
  build_runner: ^2.4.6

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
